name: Build docker containers
on:
  push:
    branches: [master]
  
jobs:
  build:
    name: Build ethstats-client
    runs-on: ubuntu-latest  
    steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          -
            name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: bfodlt/ethstats-client:latest
          -
            name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}
